// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCNtmrPn8etYHBz0Raqbfv9wpNvYkdZmc',
    appId: '1:905987890507:web:ded4a07651efdb2a085cce',
    messagingSenderId: '905987890507',
    projectId: 'fir-practice-a6a27',
    authDomain: 'fir-practice-a6a27.firebaseapp.com',
    storageBucket: 'fir-practice-a6a27.firebasestorage.app',
    measurementId: 'G-QRCK57L4D5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8xGhpxZZ4b6Wgw1LCkiX0VahVIGQ_ULw',
    appId: '1:905987890507:android:06c483fb46cd7976085cce',
    messagingSenderId: '905987890507',
    projectId: 'fir-practice-a6a27',
    storageBucket: 'fir-practice-a6a27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7da5gsq_nZKwyWcwl3ZDOEuMFqHFg9eU',
    appId: '1:905987890507:ios:5875ef23d1ed2c8c085cce',
    messagingSenderId: '905987890507',
    projectId: 'fir-practice-a6a27',
    storageBucket: 'fir-practice-a6a27.firebasestorage.app',
    iosBundleId: 'com.example.flutterTasks',
  );

}